# Generated by Django 5.2.4 on 2025-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='body',
            field=models.TextField(default='empty'),
        ),
    ]
